version: '3'
services:
  mysql:
    image: mysql:8.0.20
    ports:
      - ${MYSQL_PORT:-3306:3306}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS ktorwebapp;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
